export const technologyOptions = [
  { value: "react", label: "React" },
  { value: "vue", label: "Vue" },
  { value: "angular", label: "Angular" },
  { value: "node", label: "Node" },
  { value: "express", label: "Express" },
  { value: "next", label: "Next" },
  { value: "nestjs", label: "NestJS" },
  { value: "deno", label: "Deno" },
  { value: "svelte", label: "Svelte" },
  { value: "flutter", label: "Flutter" },
  { value: "react-native", label: "React Native" },
  { value: "ionic", label: "Ionic" },
  { value: "swift", label: "Swift" },
  { value: "kotlin", label: "Kotlin" },
  { value: "java", label: "Java" },
  { value: "spring", label: "Spring" },
  { value: "laravel", label: "Laravel" },
  { value: "django", label: "Django" },
  { value: "flask", label: "Flask" },
  { value: "rails", label: "Rails" },
  { value: "phoenix", label: "Phoenix" },
  { value: "elixir", label: "Elixir" },
  { value: "go", label: "Go" },
  { value: "rust", label: "Rust" },
  { value: "c", label: "C" },
  { value: "cpp", label: "C++" },
  { value: "csharp", label: "C#" },
  { value: "dotnet", label: ".NET" },
  { value: "python", label: "Python" },
  { value: "php", label: "PHP" },
  { value: "mysql", label: "MySQL" },
  { value: "postgresql", label: "PostgreSQL" },
  { value: "mongodb", label: "MongoDB" },
  { value: "redis", label: "Redis" },
  { value: "docker", label: "Docker" },
  { value: "kubernetes", label: "Kubernetes" },
];
