import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { UserContextProvider } from "@/contexts/UserContext";
import { ReactQueryProvider } from "@/config/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  weight: ["300", "400", "500", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${poppins.className}`}>
        <Toaster richColors position="top-right" />
        <ReactQueryProvider>
          <UserContextProvider>{children}</UserContextProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
